# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0003_auto_20171109_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Room'),
        ),
    ]
