# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0004_auto_20171109_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreposter',
            old_name='character',
            new_name='character_spt',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='media',
            new_name='media_spt',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='presentation',
            new_name='presentation_spt',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='quality',
            new_name='quality_spt',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='question',
            new_name='question_spt',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='time',
            new_name='time_spt',
        ),
    ]
