# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0005_auto_20171110_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreposter',
            old_name='character_spt',
            new_name='character_spo',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='media_spt',
            new_name='media_spo',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='presentation_spt',
            new_name='presentation_spo',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='quality_spt',
            new_name='quality_spo',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='question_spt',
            new_name='question_spo',
        ),
        migrations.RenameField(
            model_name='scoreposter',
            old_name='time_spt',
            new_name='time_spo',
        ),
    ]
