# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0006_auto_20171110_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='levels_teacher',
            field=models.IntegerField(default=1),
        ),
    ]
