# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0007_auto_20171113_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_advisor',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_co_advisor',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_major',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=1024),
        ),
    ]
