# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0008_auto_20171113_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'ตารางวันที่สอบ',
            },
        ),
        migrations.CreateModel(
            name='TimeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_exam', models.CharField(max_length=256)),
                ('time_period', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ตารางเวลา',
            },
        ),
    ]
