# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0009_dateexam_timeexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleroom',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheduleroom',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='scheduleroom',
            name='time_start',
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='date_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.DateExam'),
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='proj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Project'),
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.TimeExam'),
        ),
    ]
