# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0011_dateexam_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateexam',
            name='time_period',
            field=models.IntegerField(default=0),
        ),
    ]
